export const TYPE = {
  FETCH_MOVIES: "FETCH_MOVIES",
  MOVIE_DETAIL: "MOVIE_DETAIL",
  FETCH_SUCCESS_MOVIES: "FETCH_SUCCESS_MOVIES",

  FETCH_SUCCESS_TRENDING: "FETCH_SUCCESS_TRENDING",
  FETCH_TRENDING: "FETCH_TRENDING",
  FETCH_ERROR_TRENDING: "FETCH_ERROR_TRENDING",

  FETCH_SUCCESS_UPCOMMING: "FETCH_SUCCESS_UPCOMMING",
  FETCH_UPCOMMING: "FETCH_UPCOMMING",
  FETCH_ERROR_UPCOMMING: "FETCH_ERROR_UPCOMMING",

  FETCH_SUCCESS_TVSHOW: "FETCH_SUCCESS_TVSHOW",
  FETCH_TVSHOW: "FETCH_TVSHOW:",
  FETCH_ERROR_TVSHOW: "FETCH_ERROR_TVSHOW",

  FETCH_SUCCESS_PEOPLE: "FETCH_SUCCESS_PEOPLE",
  FETCH_PEOPLE: "FETCH_PEOPLE",
  FETCH_ERROR_TVSHOW: "FETCH_ERROR_PEOPLE",
};
