export const TYPE = {
  FETCH_MOVIES: "FETCH_MOVIES",
  FETCH_SUCCESS_MOVIES: "FETCH_SUCCESS_MOVIES",
  FETCH_ERROR_MOVIES: "FETCH_ERROR_MOVIES",

  FETCH_SUCCESS_TRENDING: "FETCH_SUCCESS_TRENDING",
  FETCH_TRENDING: "FETCH_TRENDING",
  FETCH_ERROR_TRENDING: "FETCH_ERROR_TRENDING",

  FETCH_SUCCESS_UPCOMMING: "FETCH_SUCCESS_UPCOMMING",
  FETCH_UPCOMMING: "FETCH_UPCOMMING",
  FETCH_ERROR_UPCOMMING: "FETCH_ERROR_UPCOMMING",

  FETCH_SUCCESS_TVSHOW: "FETCH_SUCCESS_TVSHOW",
  FETCH_TVSHOW: "FETCH_TVSHOW:",
  FETCH_ERROR_TVSHOW: "FETCH_ERROR_TVSHOW",

  FETCH_SUCCESS_PEOPLE: "FETCH_SUCCESS_PEOPLE",
  FETCH_PEOPLE: "FETCH_PEOPLE",
  FETCH_ERROR_TVSHOW: "FETCH_ERROR_PEOPLE",

  FETCH_MOVIE_DETAIL: "FETCH_MOVIE_DETAIL",
  FETCH_SUCCESS_MOVIE_DETAIL: "FETCH_SUCCESS_MOVIE_DETAIL",
  FETCH_ERROR_MOVIE_DETAIL: "FETCH_ERROR_MOVIE_DETAIL",

  FETCH_TV_DETAIL: "FETCH_TV_DETAIL",
  FETCH_SUCCESS_TV_DETAIL: "FETCH_SUCCESS_TV_DETAIL",
  FETCH_ERROR_TV_DETAIL: "FETCH_ERROR_TV_DETAIL",

  FETCH_PEOPLE_DETAIL: "FETCH_PEOPLE_DETAIL",
  FETCH_SUCCESS_PEOPLE_DETAIL: "FETCH_SUCCESS_PEOPLE_DETAIL",
  FETCH_ERROR_PEOPLE_DETAIL: "FETCH_ERROR_PEOPLE_DETAIL",

  FETCH_SEARCH_RESULT: "FETCH_SEARCH_RESULT",
  FETCH_SUCCESS_SEARCH_RESULT: "FETCH_SUCCESS_SEARCH_RESULT",
  FETCH_ERROR_SEARCH_RESULT: "FETCH_ERROR_SEARCH_RESULT",

  FETCH_REVIEW: "FETCH_REVIEW",
  FETCH_SUCCESS_REVIEW: "FETCH_SUCCESS_REVIEW",
  FETCH_ERROR_REVIEW: "FETCH_ERROR_REVIEW",

  FETCH_TVREVIEW: "FETCH_TVREVIEW",
  FETCH_SUCCESS_TVREVIEW: "FETCH_SUCCESS_TVREVIEW",
  FETCH_ERROR_TVREVIEW: "FETCH_ERROR_TVREVIEW",
};
